// 37-second narrated pitch demo: the single most important thing Bumply does — a mother
// writes a danger sign in Pidgin, gets an instant correct escalation, a referral
// code is issued, her CHW sees it, and her arrival at the facility is confirmed.
// That loop is what turns "an app" into measurable maternal impact.
import React from "react";
import {
  AbsoluteFill, Audio, Img, Sequence, staticFile,
  useCurrentFrame, useVideoConfig, interpolate, spring, Easing,
} from "remotion";

/** Narration track for a scene. Generated by scripts/make-vo.mts; swap the file
 *  in public/vo for a human recording of the same length and nothing else changes. */
const VO: React.FC<{ id: string }> = ({ id }) => (
  <Audio src={staticFile(`vo/${id}.wav`)} volume={1} />
);

/** Full-bleed documentary still with a slow push-in. Real Nigerian mothers and
 *  health workers, so the film is about people rather than user interface.
 *  DFID / UK Aid via Wikimedia Commons, CC BY-SA 2.0. */
const PhotoBg: React.FC<{ src: string; from?: number; to?: number; pos?: string; scrim?: string }> = ({
  src, from = 1.06, to = 1.16, pos = "center", scrim,
}) => {
  const frame = useCurrentFrame();
  const { durationInFrames } = useVideoConfig();
  const k = interpolate(frame, [0, durationInFrames], [from, to], { extrapolateRight: "clamp" });
  return (
    <AbsoluteFill>
      <Img src={staticFile(src)} style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition: pos, transform: `scale(${k})` }} />
      <AbsoluteFill style={{ background: scrim ?? "linear-gradient(90deg,rgba(18,13,11,.93) 0%,rgba(18,13,11,.78) 38%,rgba(18,13,11,.35) 68%,rgba(18,13,11,.15) 100%)" }} />
    </AbsoluteFill>
  );
};

const C = {
  cream: "#FBF7F1",
  ink: "#2E2620",
  inkMid: "#5B4A3E",
  terracotta: "#BE5A38",
  sage: "#6E8C63",
  gold: "#A98520",
  blue: "#0369A1",
  pale: "#F6E9E1",
  danger: "#C0392B",
  dangerBg: "#FDEEEA",
  // Dark-surface steps. The colours above are validated against the cream surface;
  // on ink they drop below 4.5:1 and read muddy. These are re-stepped for ink,
  // not flipped, and stay mutually distinguishable.
  terracottaOnInk: "#E0906A",
  blueOnInk: "#7FC4E8",
  sageOnInk: "#9DBE8F",
  goldOnInk: "#E8B96F",
};
const SERIF = "'Cormorant Garamond', Georgia, 'Times New Roman', serif";
const SANS = "'DM Sans', -apple-system, Segoe UI, Roboto, sans-serif";

/** Fade + rise, the only entrance used anywhere — consistency reads as craft. */
const useRise = (delay = 0, dist = 26) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const s = spring({ frame: frame - delay, fps, config: { damping: 200, mass: 0.6 } });
  return { opacity: s, transform: `translateY(${(1 - s) * dist}px)` };
};

const Bubble: React.FC<{ from: "her" | "bot"; delay: number; children: React.ReactNode; danger?: boolean }> = ({
  from, delay, children, danger,
}) => {
  const st = useRise(delay, 18);
  const her = from === "her";
  return (
    <div style={{ display: "flex", justifyContent: her ? "flex-end" : "flex-start", marginBottom: 14, ...st }}>
      <div
        style={{
          maxWidth: "78%",
          padding: "16px 20px",
          borderRadius: 22,
          borderBottomRightRadius: her ? 6 : 22,
          borderBottomLeftRadius: her ? 22 : 6,
          background: her ? C.terracotta : danger ? C.dangerBg : "#fff",
          color: her ? "#fff" : danger ? C.danger : C.ink,
          border: danger ? `2px solid ${C.danger}` : her ? "none" : "1px solid rgba(46,38,32,.10)",
          fontFamily: SANS,
          fontSize: 27,
          lineHeight: 1.45,
          fontWeight: danger ? 600 : 400,
          boxShadow: "0 6px 20px rgba(46,38,32,.06)",
        }}
      >
        {children}
      </div>
    </div>
  );
};

const Phone: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <div
    style={{
      width: 660, height: 830, borderRadius: 54, background: "#fff",
      border: `12px solid ${C.ink}`, overflow: "hidden",
      boxShadow: "0 50px 120px rgba(46,38,32,.35)", display: "flex", flexDirection: "column",
    }}
  >
    <div style={{ background: C.ink, color: "#fff", padding: "18px 26px", display: "flex", alignItems: "center", gap: 14, fontFamily: SANS }}>
      <div style={{ width: 42, height: 42, borderRadius: 21, background: C.terracotta, display: "grid", placeItems: "center", fontSize: 22 }}>🤰</div>
      <div>
        <div style={{ fontSize: 24, fontWeight: 700 }}>Bumply</div>
        <div style={{ fontSize: 17, opacity: 0.65 }}>online</div>
      </div>
    </div>
    <div style={{ flex: 1, background: C.cream, padding: "26px 24px", overflow: "hidden" }}>{children}</div>
  </div>
);

/** Scene 1 — the premise. */
const Hook: React.FC = () => {
  const a = useRise(6), b = useRise(20);
  return (
    <AbsoluteFill style={{ justifyContent: "center", padding: "0 120px" }}>
      <VO id="hook" />
      <PhotoBg src="photos/health-edu.jpg" pos="62% center"
        scrim="linear-gradient(85deg,rgba(18,13,11,.95) 0%,rgba(18,13,11,.88) 30%,rgba(18,13,11,.45) 62%,rgba(18,13,11,.2) 100%)" />
      <div style={{ ...a, position: "relative", fontFamily: SERIF, fontSize: 92, color: "#fff", lineHeight: 1.1, maxWidth: 1180 }}>
        She may never download a health app.
      </div>
      <div style={{ ...b, position: "relative", fontFamily: SERIF, fontSize: 92, color: C.goldOnInk, marginTop: 14, fontStyle: "italic" }}>
        But she is already on WhatsApp.
      </div>
    </AbsoluteFill>
  );
};

/** Scene 2 — danger sign in Pidgin gets an instant, correct escalation. */
const DangerScene: React.FC = () => {
  const label = useRise(4);
  return (
    <AbsoluteFill style={{ background: C.cream, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 90, padding: 80 }}>
      <VO id="danger" />
      <Phone>
        <Bubble from="her" delay={26}>i dey see plenty blood</Bubble>
        <Bubble from="bot" delay={96} danger>
          🚨 Blessing, this can be very serious. Abeg, GO to the nearest hospital NOW — no wait.
        </Bubble>
        <Bubble from="bot" delay={196}>
          🚕 I am alerting Musa (0803…) to carry you now.
          <br />
          <br />
          📋 Show this code at the clinic: <b>BMP-4KX9</b>
        </Bubble>
      </Phone>
      <div style={{ width: 620 }}>
        <div style={{ ...label, fontFamily: SANS, letterSpacing: ".18em", fontSize: 20, color: C.terracotta, fontWeight: 700 }}>
          THE SAFETY LAYER
        </div>
        <div style={{ ...useRise(12), fontFamily: SERIF, fontSize: 78, color: C.ink, lineHeight: 1.08, marginTop: 16 }}>
          Detected in her own words.
        </div>
        <div style={{ ...useRise(24), fontFamily: SANS, fontSize: 28, color: C.inkMid, lineHeight: 1.6, marginTop: 26 }}>
          Deterministic danger-sign detection runs <b>before</b> any AI model — in English,
          Pidgin, Yorùbá, Hausa and Igbo. It cannot be talked out of an escalation, and it
          works when the model is down.
        </div>
      </div>
    </AbsoluteFill>
  );
};

/** Scene 3 — the human loop: a CHW is pulled in, and arrival is confirmed. */
const LoopScene: React.FC = () => {
  const frame = useCurrentFrame();
  const rows = [
    { n: "Blessing A.", s: "Heavy bleeding", t: "Urgent", d: 14 },
    { n: "Amina B.", s: "BP 150/95", t: "Review", d: 26 },
    { n: "Chioma O.", s: "Fever + dizziness", t: "Review", d: 34 },
  ];
  const confirmed = frame > 96;
  const minutes = Math.round(interpolate(frame, [100, 140], [0, 47], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }));
  return (
    <AbsoluteFill style={{ background: C.cream, alignItems: "center", justifyContent: "center", padding: 90 }}>
      <VO id="loop" />
      <div style={{ ...useRise(2), fontFamily: SANS, letterSpacing: ".18em", fontSize: 20, color: C.terracotta, fontWeight: 700 }}>
        HUMAN IN THE LOOP
      </div>
      <div style={{ ...useRise(8), fontFamily: SERIF, fontSize: 82, color: C.ink, marginTop: 12, marginBottom: 44 }}>
        AI watches. A health worker acts.
      </div>
      <div style={{ display: "flex", gap: 46, alignItems: "flex-start" }}>
        <div style={{ ...useRise(12), width: 760, background: "#fff", borderRadius: 26, padding: 34, boxShadow: "0 24px 60px rgba(46,38,32,.10)" }}>
          <div style={{ fontFamily: SANS, fontSize: 22, color: C.inkMid, fontWeight: 700, marginBottom: 20 }}>CHW worklist — who needs you today</div>
          {rows.map((r) => {
            const st = useRise(r.d, 12);
            const urgent = r.t === "Urgent";
            return (
              <div key={r.n} style={{ ...st, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "18px 20px", marginBottom: 12, borderRadius: 16, background: urgent ? C.dangerBg : C.cream, border: urgent ? `2px solid ${C.danger}` : "1px solid rgba(46,38,32,.08)" }}>
                <div>
                  <div style={{ fontFamily: SANS, fontSize: 26, fontWeight: 700, color: C.ink }}>{r.n}</div>
                  <div style={{ fontFamily: SANS, fontSize: 21, color: C.inkMid }}>{r.s}</div>
                </div>
                <div style={{ fontFamily: SANS, fontSize: 19, fontWeight: 700, padding: "8px 16px", borderRadius: 100, background: urgent ? C.danger : "rgba(46,38,32,.07)", color: urgent ? "#fff" : C.inkMid }}>{r.t}</div>
              </div>
            );
          })}
        </div>
        <div style={{ ...useRise(86), width: 520 }}>
          <div style={{ borderRadius: 26, overflow: "hidden", height: 220, marginBottom: 18, boxShadow: "0 24px 60px rgba(46,38,32,.18)" }}>
            <Img src={staticFile("photos/midwife.jpg")} style={{ width: "100%", height: "100%", objectFit: "cover", objectPosition: "60% 22%" }} />
          </div>
          <div style={{ background: C.ink, color: "#fff", borderRadius: 26, padding: "30px 40px", textAlign: "center" }}>
          <div style={{ fontFamily: SANS, fontSize: 21, letterSpacing: ".12em", opacity: 0.7 }}>ARRIVAL CONFIRMED</div>
          <div style={{ fontFamily: SERIF, fontSize: 104, lineHeight: 1, margin: "10px 0 4px", color: C.goldOnInk }}>
            {confirmed ? minutes : 0}
          </div>
          <div style={{ fontFamily: SANS, fontSize: 26, opacity: 0.9 }}>minutes from danger sign<br />to facility arrival</div>
          <div style={{ marginTop: 22, fontFamily: SANS, fontSize: 20, opacity: 0.6 }}>code BMP-4KX9 · measured, not estimated</div>
        </div>
        </div>
      </div>
    </AbsoluteFill>
  );
};

/** Scene 4 — the evidence a funder actually scores. */
const ProofScene: React.FC = () => {
  const frame = useCurrentFrame();
  const sens = Math.round(interpolate(frame, [16, 70], [0, 100], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) }));
  const stats = [
    { v: `${sens}%`, l: "danger-sign sensitivity", s: "across all 5 languages", c: C.terracottaOnInk },
    { v: "₦240", l: "cost per mother / month", s: "at 10,000 mothers", c: C.blueOnInk },
    { v: "0", l: "network needed", s: "on-device offline mode", c: C.sageOnInk },
  ];
  return (
    <AbsoluteFill style={{ background: C.ink, alignItems: "center", justifyContent: "center", padding: 90 }}>
      <VO id="proof" />
      <div style={{ ...useRise(2), fontFamily: SANS, letterSpacing: ".18em", fontSize: 20, color: C.goldOnInk, fontWeight: 700 }}>MEASURED, NOT CLAIMED</div>
      <div style={{ display: "flex", gap: 70, marginTop: 52 }}>
        {stats.map((s, i) => (
          <div key={s.l} style={{ ...useRise(10 + i * 9), textAlign: "center", width: 460 }}>
            <div style={{ fontFamily: SERIF, fontSize: 150, lineHeight: 1, color: s.c }}>{s.v}</div>
            <div style={{ fontFamily: SANS, fontSize: 30, color: "#fff", marginTop: 12, fontWeight: 600 }}>{s.l}</div>
            <div style={{ fontFamily: SANS, fontSize: 23, color: "rgba(255,255,255,.6)", marginTop: 6 }}>{s.s}</div>
          </div>
        ))}
      </div>
      <div style={{ ...useRise(46), fontFamily: SANS, fontSize: 22, color: "rgba(255,255,255,.45)", marginTop: 56 }}>
        258 labelled multilingual messages · npm run eval:danger
      </div>
    </AbsoluteFill>
  );
};

/** Scene 5 — sign-off. */
const Outro: React.FC = () => (
  <AbsoluteFill style={{ alignItems: "center", justifyContent: "center" }}>
      <VO id="outro" />
      <PhotoBg src="photos/midwife.jpg" pos="62% 26%" from={1.1} to={1.02}
        scrim="radial-gradient(ellipse 62% 52% at 50% 46%,rgba(18,13,11,.86) 0%,rgba(18,13,11,.62) 55%,rgba(18,13,11,.34) 100%)" />
    <div style={{ ...useRise(4), position: "relative", fontFamily: SERIF, fontSize: 190, color: "#fff", letterSpacing: "-.02em" }}>Bumply</div>
    <div style={{ ...useRise(14), position: "relative", fontFamily: SANS, letterSpacing: ".34em", fontSize: 26, color: C.goldOnInk, marginTop: -6 }}>PREGNANCY COMPANION</div>
    <div style={{ ...useRise(26), position: "relative", fontFamily: SANS, fontSize: 30, color: "rgba(255,255,255,.86)", marginTop: 42 }}>app.bumply.mom · @My_bumplycompanionbot</div>
    <div style={{ ...useRise(38), position: "absolute", bottom: 34, fontFamily: SANS, fontSize: 17, color: "rgba(255,255,255,.42)" }}>
      Photographs: DFID / UK Aid, Nigeria · CC BY-SA 2.0
    </div>
  </AbsoluteFill>
);

export const PitchDemo: React.FC = () => {
  // Cross-fade between scenes so nothing ever cuts hard.
  return (
    <AbsoluteFill style={{ background: C.cream }}>
      <Sequence durationInFrames={143}><Hook /></Sequence>
      <Sequence from={143} durationInFrames={318}><DangerScene /></Sequence>
      <Sequence from={461} durationInFrames={184}><LoopScene /></Sequence>
      <Sequence from={645} durationInFrames={305}><ProofScene /></Sequence>
      <Sequence from={950} durationInFrames={157}><Outro /></Sequence>
    </AbsoluteFill>
  );
};
